name: Build and Release
on:
    push:
      tags:
        - "v*.*.*"
      branches:
        - main
    workflow_dispatch: null
jobs:

  build:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    runs-on: ubuntu-latest

    strategy:
        matrix:
          os:
            - linux
            - windows
            - darwin
          arch:
            - amd64
            - arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: '^1.22.4'

      - name: Build application
        run: |
            GOOS=${{ matrix.os }}
            GOARCH=${{ matrix.arch }}
            output_file="rerun-${GOOS}-${GOARCH}"
            VERSION=${GITHUB_REF#refs/tags/}  # Extract tag name

            if [ "${GOOS}" = "windows" ]; then
              output_file="${output_file}.exe"
            fi

            CGO_ENABLED=0 GOOS=${GOOS} GOARCH=${GOARCH} go build -ldflags "-X main.version=${VERSION}" -o $output_file ./main.go

            mkdir -p release/${GOOS}/${GOARCH}
            mv $output_file release/${GOOS}/${GOARCH}/
            ls -al release
            file release/${GOOS}/${GOARCH}/$output_file

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify release creation
        run: |
          tree
          echo "Release created at: ${{ steps.create_release.outputs.upload_url }}"
