name: Update Readme
on:
    push:
      tags:
        - "v*.*.*"
      branches:
        - main
    workflow_dispatch: null
jobs:

  update-readme:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "codeharik"
          git config user.email "codeharik@gmail.com"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: '^1.22.4'
      - name: Build and run Go application
        run: |
            VERSION=${GITHUB_REF#refs/tags/}
            echo $VERSION
            go build -ldflags "-X main.version=${VERSION}" -o rerun ./main.go
            ./rerun >> message.txt

      - name: Update README with envsubst
        run: |
          export MESSAGE=$(cat message.txt)
          envsubst < .github/READ.tmpl > README.md
          cat README.md

      - name: Commit and push changes
        run: |
          git fetch origin main
          git checkout main
          git pull origin main
          VERSION=${GITHUB_REF#refs/tags/}
          git add README.md
          git commit -m "Update README with latest message from main.go ${VERSION}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          