name: Update Readme
on:
    push:
      tags:
        - "v*.*.*"
      branches:
        - main
    workflow_dispatch: null
jobs:

  update-readme:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "codeharik"
          git config user.email "codeharik@gmail.com"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
            go-version: '^1.22.4'
      - name: Build and run Go application
        run: |
            VERSION=${GITHUB_REF#refs/tags/}
            echo $VERSION
            go run tools/generate.go -v=$VERSION

      - name: Commit and push changes
        run: |
          git fetch origin main
          git checkout main
          git pull origin main
          VERSION=${GITHUB_REF#refs/tags/}
          git add .
          git commit -m "Update README ${VERSION}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          